// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// MultipleGGMs_SSSL_DGDP
void MultipleGGMs_SSSL_DGDP(int n, int M, int Ngroups, int pcovs, std::vector<int> groups_dim, Rcpp::NumericMatrix& Ydata, Rcpp::NumericMatrix& Xdata, float alpha_a, float alpha_b, int K, float pi_a, float pi_b, float v0, float h, float lambda_Sigma, float scale_global, float scale_proposal, int iterations, int burn_in, int tinning, Rcpp::NumericMatrix out_Omega, Rcpp::IntegerMatrix out_Z, Rcpp::NumericMatrix out_pi, Rcpp::IntegerMatrix out_cind, Rcpp::NumericMatrix out_beta, Rcpp::IntegerVector out_nclus, Rcpp::IntegerVector out_acc_alpha, Rcpp::NumericMatrix out_alpha_mu);
RcppExport SEXP _NPMGGM_MultipleGGMs_SSSL_DGDP(SEXP nSEXP, SEXP MSEXP, SEXP NgroupsSEXP, SEXP pcovsSEXP, SEXP groups_dimSEXP, SEXP YdataSEXP, SEXP XdataSEXP, SEXP alpha_aSEXP, SEXP alpha_bSEXP, SEXP KSEXP, SEXP pi_aSEXP, SEXP pi_bSEXP, SEXP v0SEXP, SEXP hSEXP, SEXP lambda_SigmaSEXP, SEXP scale_globalSEXP, SEXP scale_proposalSEXP, SEXP iterationsSEXP, SEXP burn_inSEXP, SEXP tinningSEXP, SEXP out_OmegaSEXP, SEXP out_ZSEXP, SEXP out_piSEXP, SEXP out_cindSEXP, SEXP out_betaSEXP, SEXP out_nclusSEXP, SEXP out_acc_alphaSEXP, SEXP out_alpha_muSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type Ngroups(NgroupsSEXP);
    Rcpp::traits::input_parameter< int >::type pcovs(pcovsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type groups_dim(groups_dimSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type Ydata(YdataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type Xdata(XdataSEXP);
    Rcpp::traits::input_parameter< float >::type alpha_a(alpha_aSEXP);
    Rcpp::traits::input_parameter< float >::type alpha_b(alpha_bSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< float >::type pi_a(pi_aSEXP);
    Rcpp::traits::input_parameter< float >::type pi_b(pi_bSEXP);
    Rcpp::traits::input_parameter< float >::type v0(v0SEXP);
    Rcpp::traits::input_parameter< float >::type h(hSEXP);
    Rcpp::traits::input_parameter< float >::type lambda_Sigma(lambda_SigmaSEXP);
    Rcpp::traits::input_parameter< float >::type scale_global(scale_globalSEXP);
    Rcpp::traits::input_parameter< float >::type scale_proposal(scale_proposalSEXP);
    Rcpp::traits::input_parameter< int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< int >::type tinning(tinningSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type out_Omega(out_OmegaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type out_Z(out_ZSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type out_pi(out_piSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type out_cind(out_cindSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type out_beta(out_betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type out_nclus(out_nclusSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type out_acc_alpha(out_acc_alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type out_alpha_mu(out_alpha_muSEXP);
    MultipleGGMs_SSSL_DGDP(n, M, Ngroups, pcovs, groups_dim, Ydata, Xdata, alpha_a, alpha_b, K, pi_a, pi_b, v0, h, lambda_Sigma, scale_global, scale_proposal, iterations, burn_in, tinning, out_Omega, out_Z, out_pi, out_cind, out_beta, out_nclus, out_acc_alpha, out_alpha_mu);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NPMGGM_MultipleGGMs_SSSL_DGDP", (DL_FUNC) &_NPMGGM_MultipleGGMs_SSSL_DGDP, 28},
    {NULL, NULL, 0}
};

RcppExport void R_init_NPMGGM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
