# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MultipleGGMs_SSSL_DGDP <- function(n, M, Ngroups, pcovs, groups_dim, Ydata, Xdata, alpha_a, alpha_b, K, pi_a, pi_b, v0, h, lambda_Sigma, scale_global, scale_proposal, iterations, burn_in, tinning, out_Omega, out_Z, out_pi, out_cind, out_beta, out_nclus, out_acc_alpha, out_alpha_mu) {
    invisible(.Call(`_NPMGGM_MultipleGGMs_SSSL_DGDP`, n, M, Ngroups, pcovs, groups_dim, Ydata, Xdata, alpha_a, alpha_b, K, pi_a, pi_b, v0, h, lambda_Sigma, scale_global, scale_proposal, iterations, burn_in, tinning, out_Omega, out_Z, out_pi, out_cind, out_beta, out_nclus, out_acc_alpha, out_alpha_mu))
}

